[package]
name = "github-comment"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.2", features = ["derive"] }
octocrab = "0.35.0"
tokio = { version = "1.36.0", features = ["full"] }
